OOP school library: set up associations
AdnanOlarmmi/School-Library pull request #4
Opened 2022-12-22 15:07 UTC by AdnanOlarmmi

# OOP school library: set up associations

Hi Reviewer, 
![Patrick Hi](https://user-images.githubusercontent.com/41163571/197515690-1052a317-9af9-4a6a-827a-85f1a29234f4.gif)

## Learning objectives
- Run a program using the command line.
- Set up associations between classes and objects.

## Description
In this project, I finished creating the remaining classes for the school library and created the associations between them.

### General requirements

- Made sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Made sure that I used correctly [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Made sure that I documented my work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

### Ruby requirements
- Followed the list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

### Project requirements
- Created a class `Classroom` with the following:
  - `@label` instance variable, was initialized in the constructor.
  - Setter and getter for `@label` (remembered about `attr_accessor`).
- Created the `has-many`/`belongs-to` relationship between `Classroom` and `Student`. The following was implemented:
  - Created the `has-many` side (a classroom has many students).
  - Created the `belongs-to` side (a student belongs to a classroom).
  - Made sure that when adding a student to a classroom it also sets the classroom for the student.
  - Made sure that when setting the classroom for a student it also adds it to the classrooms' students.
- Created a class `Book` with the following:
  - `@title` and `@author` instance variables, should be initialized in the constructor.
  - Setters and getters for instance variables (remembered about `attr_accessor`).
- Created a class `Rental` with the following:
  - `@date` instance variable, was initialized in the constructor.
  - Setter and getter for `@date` (remembered about `attr_accessor`).
- Created the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`. The following was implemented:
  - Created the `has-many` side of `Book` and `Rental` (a book has many rentals).
  - Created the `belongs-to` side of `Rental` and `Book` (a rental belongs to a book).
  - Created the `has-many` side of `Person` and `Rental` (a person has many rentals).
  - Created the `belongs-to` side of `Rental` and `Person` (a rental belongs to a person).
  - Modified the constructor of `Rental` so `Book` and `Person` are set in it.

## Appreciation
- Thanks for the review, it means a lot 🙃 

------

2022-12-22 16:09 UTC, mckent05 requested changes
Hi @AdnanOlarmmi, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 16:09 UTC, mckent05 commented on classroom.rb
> +  def initialize(label, _students)
- You do not need a student instance variable when creating a new `Classroom`, I suggest that you remove this 🙏.  You should only have the `label` as the instance variable 😄

2022-12-22 16:09 UTC, mckent05 commented on classroom.rb
> +  end
- Good job setting up the `has-many` relationship, but when adding a student to a classroom, you need to complete this association by assigning the classroom to the student also. You can refer to this [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships) for more info. I suggest adding `student.classroom=self`. Please fix this 👍 👍

2022-12-22 16:09 UTC, mckent05 commented on student.rb
> +require_relative 'classroom'
- A student should belong to a classroom, please implement the `belongs-to` relationship method in your `Student` class. Refer to this [article](`https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships`) for more info 😄 😄

2022-12-22 16:09 UTC, mckent05 commented on book.rb
> +end
- Please implement a `has-many` relationship between your book class and the rental class by initializing a `@rentals=[]`, this would mean a book can have many rentals. Please fix this 👍 👍 
- A method for adding rentals to your book should be present, please fix this 😄. Refer to this [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) for more info. This would ensure the `has-many` relationship is achieved 👍  
## In your `Person.rb` file:
- Please implement a `has-many` relationship between the `Person` class and the `rental` class, a person can have many rentals.
- Implement a method to achieve the `has-many` relationship just like you will do for the `book` class. Please fix this 😄

2022-12-23 14:41 UTC, sumairq approved these changes
### Hi @AdnanOlarmmi , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 14:45 UTC, merged